config/routes.rb
Osem::Application.routes.draw do
  # concerns
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  # Problem children
  get '/2017',
    to: redirect('http://2017.linuxfestnorthwest.org/2017', status: 302)

  # Root
  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  # short urls
  if ENV['OSEM_ROOT_CONFERENCE'].present?
    get '/register', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/register/new")
    get '/schedule', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/schedule/events")
  end


  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path:        'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  get '/checkin',
    to: redirect('/admin/ticket_scannings', status: 302)

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resources :ticket_scannings, only: [:index, :create, :new]
    get '/scan_ticket/:token' => 'ticket_scannings#new', as: 'scan_ticket'


    resources :comments, only: [:index]
    resources :conferences do
      resources :surveys do
        resources :survey_questions, except: :index
      end
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations do
        member do
          patch :toggle_attendance
          patch :toggle_code_of_conduct
        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events, concerns: [:with_datatable] do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          collection do
            get :voting_queue
            get :speakers
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets do
        get 'materials', on: :collection
        post 'import', on: :collection
        post 'give', on: :member
      end
      resources :sponsors, except: [:show] do
        post 'import', on: :collection
      end
      resources :lodgings, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        post 'import', on: :collection
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences, 'code-of-conduct'
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resources :surveys, only: [:index, :show] do
      member do
        post :reply
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
        get :kiosk
        get :print
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  unless ENV['OSEM_ROOT_CONFERENCE'].blank?
    root to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}")
  else
    root to: 'conferences#index', via: [:get, :options]
  end
end

app/models/survey.rb
# frozen_string_literal: true

class Survey < ActiveRecord::Base
  belongs_to :surveyable, polymorphic: true
  has_many :survey_questions, dependent: :destroy
  has_many :survey_submissions, dependent: :destroy

  enum target: [:after_conference, :during_registration, :after_event]
  validates :title, presence: true

  ##
  # Finds active surveys
  # * if a survey has either start or end date, but not both
  # check is performed only on the attribute that exists
  # * if a survey does not have start/end dates, then it is marked active
  # further check is expected, where appropriate, depending on the survey's target
  # ====Returns
  # * +true+ -> If the survey is active (will accept replies)
  # * +false+ -> If the survey is closed
  def active?
    return true unless start_date || end_date

    # Find timezone of conference (survyeable is Conference or Event)
    timezone = surveyable.is_a?(Conference) ? surveyable.timezone : surveyable.conference.timezone
    now = Time.current.in_time_zone(timezone)

    if start_date && end_date
      now >= start_date && now <= end_date
    elsif start_date && !end_date
      now >= start_date
    elsif !start_date && end_date
      now <= end_date
    end
  end
end

app/controllers/admin/surveys_controller.rb
# frozen_string_literal: true

module Admin
  class SurveysController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource

    def index
      @surveys = @conference.surveys + Survey.where(surveyable: @conference.program.events)
    end

    def new
      @survey = Survey.new(survey_params)
      @url = admin_conference_surveys_path(@conference.short_title)
    end

    def create
      @survey = Survey.new(survey_params)
      if @survey.save
        redirect_to new_admin_conference_survey_survey_question_path(@conference.short_title, @survey), notice: 'Successfully created survey'
      else
        redirect_to new_admin_conference_survey_survey_question_path(@conference.short_title, @survey), error: 'Could not create survey.' + @survey.errors.full_messages.to_sentence
      end
    end

    def edit
      @url = admin_conference_survey_path(@conference.short_title, @survey)
    end

    def update
      if @survey.update_attributes(survey_params)
        redirect_to admin_conference_surveys_path(@conference.short_title)
      else
        @url = admin_conference_survey_path(@conference.short_title, @survey)
        render action: :edit
      end
    end

    def destroy
      @survey.destroy
      redirect_to admin_conference_surveys_path(@conference.short_title)
    end

    private

    def survey_params
      params.require(:survey).permit(:title, :description, :target, :start_date, :end_date, :surveyable_type, :surveyable_id)
    end
  end
end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController
  load_resource :conference, find_by: :short_title
  load_and_authorize_resource except: :reply
  load_resource only: :reply
  skip_authorization_check only: :reply

  def index
    @surveys = @conference.surveys.select(&:active?)
  end

  def show
    @survey_submission = @survey.survey_submissions.new
  end

  def reply
    unless can? :reply, @survey
      redirect_to conference_survey_path(@conference, @survey), alert: 'This survey is currently closed'
      return
    end

    survey_submission = params[:survey_submission]

    @survey.survey_questions.each do |survey_question|
      reply = survey_question.survey_replies.find_by(user: current_user)
      reply_text = survey_submission[survey_question.id.to_s].reject(&:blank?).join(',')

      if reply
        reply.update_attributes(text: reply_text) unless reply.text == reply_text
      else
        survey_question.survey_replies.create!(text: reply_text, user: current_user)
      end

      user_survey_submission = @survey.survey_submissions.find_by(user: current_user)
      if user_survey_submission
        user_survey_submission.update_attributes(updated_at: Time.current)
      else
        @survey.survey_submissions.create!(user: current_user)
      end
    end

    case @survey.target
    when 'during_registration'
      redirect_to conference_conference_registration_path(@conference.short_title)
    else
      redirect_back fallback: root_path
    end
  end
end

app/views/admin/surveys/_form.html.haml
.row
  .col-md-12
    .page-header
      - if @survey.new_record?
        %h1 New Survey
      - else
        %h1 Edit Survey: #{ @survey.title }

  .col-md-6
    = semantic_form_for @survey, url: @url do |f|
      = f.hidden_field :surveyable_type
      = f.hidden_field :surveyable_id
      = f.input :title
      = f.input :description, input_html: { rows: 3 }
      = f.input :target, as: :select, collection: Survey.targets.keys, label: "When to ask"
      = f.input :start_date, as: :string, input_html: { class: 'datetimepicker' }
      = f.input :end_date, as: :string, input_html: { class: 'datetimepicker' }
      = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/surveys/_survey_question.html.haml
.panel.panel-default
  .panel-heading
    = render partial: 'admin/surveys/survey_question_title',  locals:  { survey_question: survey_question, question_index: question_index }
  .panel-body
    - if survey_question.boolean?
      %input{ type: 'hidden', name: "survey_submission[#{survey_question.id}][]" }
      %label
        %input{ type: 'radio', name: "survey_submission[#{survey_question.id}][]", value: 'Yes', checked: survey_reply.text == 'Yes',required: survey_question.mandatory }
        Yes
      %br
      %label
        %input{ type: 'radio', name: "survey_submission[#{survey_question.id}][]", value: 'No', checked: survey_reply.text == 'No' }
        No

    - elsif survey_question.choice?
      %input{ type: 'hidden', name: "survey_submission[#{survey_question.id}][]" }
      - possible_answers = survey_question.possible_answers.split(',').map(&:strip)

      - possible_answers.each.with_index(1) do |answer, answer_index|
        - if survey_question.single_choice?
          %label
            %input{ type: 'radio', name: "survey_submission[#{survey_question.id}][]", value: answer, checked: (survey_reply.text == answer if survey_reply.text), required: survey_question.mandatory }
            = answer
          %br
        - else
          %label
            = check_box_tag "survey_submission[#{survey_question.id}][]", answer, (survey_reply.text.include? answer if survey_reply.text), id: dom_id(survey_reply), required: survey_question.mandatory
            = answer

          %br
    - elsif survey_question.string?
      %input.form-control{ name: "survey_submission[#{survey_question.id}][]", value:  survey_reply.text, required: survey_question.mandatory }
    - elsif survey_question.text?
      = text_area_tag "survey_submission[#{survey_question.id}][]", survey_reply.text, rows: 4, class: 'form-control', required: survey_question.mandatory
    - elsif survey_question.datetime?
      .form-group{ class: 'datetimepicker' }
        .input-group
          .input-group-addon
            %span.fa.fa-calendar
          %input.form-control{ readonly: 'readonly', name: "survey_submission[#{survey_question.id}][]", value: survey_reply.text, required: survey_question.mandatory }
    - elsif survey_question.numeric?
      %input.form-control{ type: 'number', name: "survey_submission[#{survey_question.id}][]", value: survey_reply.text, required: survey_question.mandatory }

app/views/admin/surveys/_survey_question_title.html.haml
%span.badge
  = question_index
= survey_question.title

- if survey_question.multiple_choice?
  ( Select
  - if survey_question.min_choices != survey_question.max_choices
    a minimum of
  = survey_question.min_choices
  - if survey_question.min_choices != survey_question.max_choices
    and a maximum of
    = survey_question.max_choices
  choices )
- if survey_question.mandatory
  %span.fa.fa-asterisk.text-danger
- if can? :edit, @survey
  %p.pull-right
    = "(#{survey_question.survey_replies.count} replies)"
    = link_to edit_admin_conference_survey_survey_question_path(@conference.short_title, @survey, survey_question) do
      %span.fa.fa-edit
    = link_to admin_conference_survey_survey_question_path(@conference.short_title, @survey, survey_question), method: :delete, data: { confirm: 'Are you sure you want to delete this question?' } do
      %span.fa.fa-times

app/views/admin/surveys/_survey_replies.html.haml
- @survey.survey_questions.each.with_index(1) do |survey_question, question_index|
  .panel.panel-default
    .panel-heading{ type: 'button', 'data-toggle': 'collapse', 'data-target': "#question-#{survey_question.id}", 'aria-expanded': 'true', 'aria-controls': 'collapse' }
      = render partial: 'survey_question_title', locals:  { survey_question: survey_question, question_index: question_index }

    .panel-body.collapse{ id: "question-#{survey_question.id}" }
      - if survey_question.survey_replies.any?
        %table.table
          %thead
            %th User Email
            %th Reply
          %tbody
            - survey_question.survey_replies.reload.each do |reply|
              %tr
                %td= reply.user.email
                %td= reply.text

app/views/admin/surveys/_survey_stats.html.haml
= bar_chart @survey.survey_questions.map{ |q| [q.title, q.survey_replies.count] }

- @survey.survey_questions.each.with_index(1) do |survey_question, question_index|
  .panel.panel-default
    .panel-heading
      = render partial: 'survey_question_title', locals:  { survey_question: survey_question, question_index: question_index }
    .panel-body
      - question_replies = survey_question.survey_replies
      - if question_replies.any?
        = pie_chart question_replies.group(:text).count, library: { legend: 'bottom', plotOptions: { pie: { dataLabels: { enabled: false }, showInLegend: true } } }

app/views/admin/surveys/edit.html.haml
= render partial: 'form'

app/views/admin/surveys/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Surveys
        = link_to 'New', new_admin_conference_survey_path(@conference.short_title, survey: {  surveyable_type: 'Conference', surveyable_id: @conference.id }), class: 'btn btn-success pull-right'
      %p.text-muted
        Available surveys for this conference


- if @surveys.any?
  .row
    .col-md-12
      %table.table.table-hover.datatable#surveys
        %thead
          %th Title
          %th # of questions
          %th # of submissions
          %th When
          %th Start Date
          %th End Date
          %th Actions
        %tbody
          - @surveys.each_with_index do |survey, index|
            %tr
              %td
                = link_to survey.title, admin_conference_survey_path(@conference.short_title, survey)
              %td
                = survey.survey_questions.length
              %td
                = survey.survey_submissions.length
              %td
                = survey.target
              %td
                = survey.start_date
              %td
                = survey.end_date
              %td
                .btn-group
                  = link_to 'Edit', edit_admin_conference_survey_path(@conference.short_title, survey),
                  class: 'btn btn-primary'
                  = link_to 'Delete', admin_conference_survey_path(@conference.short_title, survey),
                  method: :delete, class: 'btn btn-danger',
                  data: { confirm: "Do you really want to delete #{survey.title}?"}

app/views/admin/surveys/new.html.haml
= render partial: 'form'

app/views/admin/surveys/show.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Survey: #{@survey.title}
        = link_to 'Edit Survey', edit_admin_conference_survey_path(@conference.short_title, @survey), class: 'btn btn-primary pull-right'
      %p.text-muted
        From:
        = @survey.start_date
        to
        = @survey.end_date
.row
  .col-md-12
    .tabbable
      %ul.nav.nav-tabs
        %li.active
          = link_to 'Questions' , '#questions-content', 'data-toggle' => 'tab'
        %li
          = link_to 'Replies' , '#replies-content', 'data-toggle' => 'tab'
        %li
          = link_to 'Stats' , '#stats-content', 'data-toggle' => 'tab'
      .tab-content
        .tab-pane.active#questions-content
          = semantic_form_for 'survey_submission', url: '#' do |f|
            - @survey.survey_questions.each.with_index(1) do |survey_question, question_index|
              .row
                .col-md-12
                  - survey_reply = survey_question.survey_replies.new(survey_question_id: survey_question.id, user_id: current_user.id)
                  = render partial: 'survey_question', locals:  { survey_question: survey_question, question_index: question_index, survey_reply: survey_reply }
          = link_to 'Add Question', new_admin_conference_survey_survey_question_path(@conference.short_title, @survey), class: 'btn btn-success pull-right'
        .tab-pane#replies-content
          = render partial: 'survey_replies'
        .tab-pane#stats-content
          = render partial: 'survey_stats'