config/routes.rb
Osem::Application.routes.draw do
  # concerns
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  # Problem children
  get '/2017',
    to: redirect('http://2017.linuxfestnorthwest.org/2017', status: 302)

  # Root
  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  # short urls
  if ENV['OSEM_ROOT_CONFERENCE'].present?
    get '/register', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/register/new")
    get '/schedule', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/schedule/events")
  end


  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path:        'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  get '/checkin',
    to: redirect('/admin/ticket_scannings', status: 302)

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resources :ticket_scannings, only: [:index, :create, :new]
    get '/scan_ticket/:token' => 'ticket_scannings#new', as: 'scan_ticket'


    resources :comments, only: [:index]
    resources :conferences do
      resources :surveys do
        resources :survey_questions, except: :index
      end
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations do
        member do
          patch :toggle_attendance
          patch :toggle_code_of_conduct
        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events, concerns: [:with_datatable] do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          collection do
            get :voting_queue
            get :speakers
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets do
        get 'materials', on: :collection
        post 'import', on: :collection
        post 'give', on: :member
      end
      resources :sponsors, except: [:show] do
        post 'import', on: :collection
      end
      resources :lodgings, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        post 'import', on: :collection
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences, 'code-of-conduct'
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resources :surveys, only: [:index, :show] do
      member do
        post :reply
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
        get :kiosk
        get :print
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  unless ENV['OSEM_ROOT_CONFERENCE'].blank?
    root to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}")
  else
    root to: 'conferences#index', via: [:get, :options]
  end
end

app/models/booth.rb
# frozen_string_literal: true

class Booth < ApplicationRecord
  include ActiveRecord::Transitions
  has_paper_trail ignore: [:updated_at], meta: { conference_id: :conference_id }

  belongs_to :conference
  has_many :booth_requests, dependent: :destroy
  has_many :users, through: :booth_requests

  has_one :submitter_booth_user, -> { where(role: 'submitter') }, class_name: 'BoothRequest'
  has_one  :submitter, through: :submitter_booth_user, source: :user

  has_many :responsibles_booth_user, -> { where(role: 'responsible') }, class_name: 'BoothRequest'
  has_many :responsibles, through: :responsibles_booth_user, source: :user

  validates :title,
            uniqueness: { case_sensitive: false },
            presence:   true

  validates :description,
            :reasoning,
            :state,
            :responsibles,
            :conference_id,
            :website_url,
            :submitter_relationship,
            presence: true

  scope :accepted, -> { where(state: 'accepted') }
  scope :confirmed, -> { where(state: 'confirmed') }

  mount_uploader :picture, PictureUploader, mount_on: :logo_link

  state_machine initial: :new do
    state :new
    state :withdrawn
    state :to_accept
    state :accepted
    state :to_reject
    state :rejected
    state :canceled
    state :confirmed

    event :restart do
      transitions to: :new, from: [:withdrawn, :rejected, :canceled]
    end
    event :withdraw do
      transitions to: :withdrawn, from: [:new, :to_accept, :accepted, :to_reject, :rejected, :confirmed]
    end
    event :confirm do
      transitions to: :confirmed, from: [:accepted]
    end
    event :to_accept do
      transitions to: :to_accept, from: [:new, :to_reject]
    end
    event :to_reject do
      transitions to: :to_reject, from: [:new, :to_accept]
    end
    event :accept do
      transitions to: :accepted, from: [:new, :to_accept]
    end
    event :reject do
      transitions to: :rejected, from: [:new, :to_reject]
    end
    event :cancel do
      transitions to: :canceled, from: [:accepted, :rejected, :to_accept, :to_reject, :confirmed]
    end
  end

  def transition_possible?(transition)
    self.class.state_machine.events_for(current_state).include?(transition)
  end

  def update_state(transition, _notice)
    alert = ''
    begin
      send(transition)
      save
    rescue Transitions::InvalidTransition => e
      alert = "Update state failed. #{e.message}"
    end
    alert
  end
end

app/controllers/admin/booths_controller.rb
# frozen_string_literal: true

module Admin
  class BoothsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource through: :conference

    def index
      @file_name = "booths_for_#{@conference.short_title}"
      @booth_export_option = params[:booth_export_option]
      respond_to do |format|
        format.html
        # Explicity call #to_json to avoid the use of EventSerializer
        format.json { render json: Booth.where(state: :confirmed, program: @program).to_json }
        format.xlsx do
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@file_name}.xlsx\""
          render 'booths'
        end
        format.pdf { render 'booths' }
        format.csv do
          response.headers['Content-Disposition'] = "attachment; filename=\"#{@file_name}.csv\""
          render 'booths'
        end
      end
    end

    def show; end

    def new
      @url = admin_conference_booths_path(@conference.short_title)
    end

    def create
      @url = admin_conference_booths_path(@conference.short_title)

      @booth = @conference.booths.new(booth_params)

      @booth.submitter = current_user

      if @booth.save
        redirect_to admin_conference_booths_path,
                    notice: 'Booth successfully created.'
      else
        flash.now[:error] = "Creating booth failed. #{@booth.errors.full_messages.to_sentence}."
        render :new
      end
    end

    def edit
      @url = admin_conference_booth_path(@conference.short_title, @booth.id)
    end

    def update
      @url = admin_conference_booth_path(@conference.short_title, @booth.id)

      @booth.update_attributes(booth_params)

      if @booth.save
        redirect_to admin_conference_booths_path,
                    notice: "Successfully updated booth for #{@booth.title}."
      else
        flash.now[:error] = "An error prohibited the Booth for #{@booth.title} "\
                    "#{@booth.errors.full_messages.join('. ')}."
        render :edit
      end
    end

    def accept
      @booth.accept!

      if @booth.save
        if @conference.email_settings.send_on_booths_acceptance
          Mailbot.conference_booths_acceptance_mail(@booth).deliver
        end
        redirect_to admin_conference_booths_path(conference_id: @conference.short_title),
                    notice: 'Booth successfully accepted!'
      else
        redirect_to admin_conference_booths_path(conference_id: @conference.short_title)
        flash[:error] = "Booth could not be accepted. #{@booth.errors.full_messages.to_sentence}."
      end
    end

    def to_accept
      update_state(:to_accept, 'Booth to accept')
    end

    def to_reject
      update_state(:to_reject, 'Booth to reject')
    end

    def reject
      @booth.reject!

      if @booth.save
        Mailbot.conference_booths_rejection_mail(@booth).deliver
        redirect_to admin_conference_booths_path(conference_id: @conference.short_title),
                    notice: 'Booth successfully rejected.'
      else
        redirect_to admin_conference_booths_path(conference_id: @conference.short_title)
        flash[:error] = "Booth could not be rejected. #{@booth.errors.full_messages.to_sentence}."
      end
    end

    def restart
      update_state(:restart, 'Booth is submitted')
    end

    def cancel
      update_state(:cancel, 'Booth is canceled')
    end

    def confirm
      update_state(:confirm, 'Booth successfully confirmed')
    end

    private

    def update_state(transition, notice)
      alert = @booth.update_state(transition, notice)

      if alert.blank?
        flash[:notice] = notice
        redirect_back_or_to(admin_conference_booths_path(conference_id: @conference.short_title)) && return
      else
        flash[:error] = alert
        return redirect_back_or_to(admin_conference_booths_path(conference_id: @conference.short_title)) && return
      end
    end

    def booth_params
      params.require(:booth).permit(:title, :description, :reasoning, :state, :picture, :conference_id,
                                    :created_at, :updated_at, :submitter_relationship, :website_url, responsible_ids: [])
    end
  end
end

app/controllers/booths_controller.rb
# frozen_string_literal: true

class BoothsController < ApplicationController
  before_action :authenticate_user!
  load_resource :conference, find_by: :short_title
  load_and_authorize_resource through: :conference
  skip_authorize_resource only: [:withdraw, :confirm, :restart]

  def index
    @booths = current_user.booths.where(conference_id: @conference.id).uniq
  end

  def show; end

  def new
    @url = conference_booths_path(@conference.short_title)
  end

  def create
    @url = conference_booths_path(@conference.short_title)

    @booth.submitter = current_user

    if @booth.save
      redirect_to conference_booths_path,
                  notice: 'Booth successfully created.'
    else
      flash.now[:error] = "Creating booth failed. #{@booth.errors.full_messages.to_sentence}."
      render :new
    end
  end

  def edit
    @url = conference_booth_path(@conference.short_title, @booth.id)
  end

  def update
    @url = conference_booth_path(@conference.short_title, @booth.id)
    @booth.update_attributes(booth_params)

    if @booth.save
      redirect_to conference_booths_path,
                  notice: 'Booth successfully updated!'
    else
      flash.now[:error] = "Booth could not be updated. #{@booth.errors.full_messages.to_sentence}."
    end
  end

  def destroy; end

  def withdraw
    authorize! :update, @booth
    @url = conference_booth_path(@conference.short_title, @booth.id)

    @booth.withdraw!

    if @booth.save
      redirect_to conference_booths_path,
                  notice: 'Booth successfully withdrawn'
    else
      flash.now[:error] = "Booth could not be withdrawn. #{@booth.errors.full_messages.to_sentence}."
    end
  end

  def confirm
    authorize! :update, @booth
    @url = conference_booth_path(@conference.short_title, @booth.id)

    @booth.confirm!

    if @booth.save
      redirect_to conference_booths_path,
                  notice: 'Booth successfully confirmed'
    else
      flash.now[:error] = "Booth could not be confirmed. #{@booth.errors.full_messages.to_sentence}."
    end
  end

  def restart
    authorize! :update, @booth
    @url = conference_booth_path(@conference.short_title, @booth.id)

    @booth.restart!

    if @booth.save
      redirect_to conference_booths_path,
                  notice: 'Booth successfully re-submitted'
    else
      flash.now[:error] = "Booth could not be re-submitted. #{@booth.errors.full_messages.to_sentence}."
    end
  end

  private

  def booth_params
    params.require(:booth).permit(:title, :description, :reasoning, :state, :picture, :conference_id,
                                  :created_at, :updated_at, :submitter_relationship, :website_url, responsible_ids: [])
  end
end

app/views/booths/_form.html.haml
.container
  .row
    .col-md-8
      = semantic_form_for(@booth,  url: @url, html: { multipart: true }) do |f|
        = f.input :title, as: :string, input_html: { autofocus: true }, required: true
        = f.input :description, input_html: { rows: 5, data: { provide: 'markdown-editable' } }, required: true,
          hint: 'This field becomes public upon request acceptance'
        = f.input :reasoning, input_html: { rows: 5, data: { provide: 'markdown-editable' } }, required: true,
          label: 'How it fits the conference'
        = f.input :submitter_relationship, input_html: { rows: 5, data: { provide: 'markdown-editable' } }, required: true,
          label: 'Submitter\'s relation',
          hint: 'e.g. employee, comunity manager, etc'
        = f.input :website_url
        = responsibles_selector_input f
        = image_tag f.object.picture.thumb.url if f.object.picture?
        = f.input :picture

        %p.text-right
          - if @booth.new_record?
            = f.submit 'Create Booth Request', class: 'btn btn-success'
          - else
            = f.submit 'Update Booth Request', class: 'btn btn-success'

  :javascript
    $(document).ready(function() {
      $('#booth_responsible_ids').selectize({
        plugins: ['remove_button'],
        minItems: 2
      } )
    });

app/views/booths/edit.html.haml
.container
  %h1
    Editing
    = @booth.title

  = render 'form'

app/views/booths/index.html.haml
.container
  .row
    .col-md-12.page-header
      %h1
        Your booth requests for
        = @conference.title
  .row
    .col-md-12
      .margin-booth-table
        %table.table.table-striped.table-hover
          %thead
            %th
              %b State
            %th
              %b Logo
            %th
              %b Title
            %th
              %b Actions
          - @booths.each do |booth|
            %tr
              %td{ style: "padding:20px 8px 20px 8px;" }
                - if (booth.state == 'to_accept' || booth.state == 'to_reject')
                  - show_state = 'new'
                - else
                  - show_state = booth.state
                %span{ title: show_state, class: "fa #{status_icon(booth)}" }
              %td
                - if booth.logo_link
                  = image_tag(booth.picture.thumb.url, width: '20%')
              %td
                = link_to booth.title, conference_booth_path(@conference.short_title, booth)
              %td
                -if can? :edit, booth
                  = link_to 'Edit', edit_conference_booth_path(@conference.short_title, booth.id),
                    class: 'btn btn-default'
                - if booth.transition_possible? :withdraw
                  = link_to 'Withdraw',
                    withdraw_conference_booth_path(@conference.short_title, booth),
                    method: :patch, class: 'btn btn-mini btn-warning', id: "withdraw_booth_#{booth.id}",
                    data: { confirm: 'Are you sure you really want to withdraw this request?' }
                - if booth.transition_possible? :confirm
                  = link_to 'Confirm',
                    confirm_conference_booth_path(@conference.short_title, booth),
                    method: :patch, class: 'btn btn-mini btn-success', id: "confirm_booth_#{booth.id}"
                - if booth.transition_possible? :restart
                  = link_to 'Re-submit',
                    restart_conference_booth_path(@conference.short_title, booth),
                    method: :patch, class: 'btn btn-mini btn-success', id: "restart_booth_#{booth.id}"
      .pull-right
        = link_to 'Add Booth', new_conference_booth_path(@conference.short_title), class: 'button btn btn-primary'

app/views/booths/new.html.haml
.container
  %h1 Request a booth

  = render 'form'

app/views/booths/show.html.haml
.container
  .row
    .col-md-12
      %h3
        - if @booth.logo_link
          = image_tag(@booth.picture.thumb.url, size: '20%', alt: '')
        = @booth.title
        .btn-group.pull-right
          = link_to 'Edit', edit_conference_booth_path(@conference.short_title, @booth), class: 'btn btn-mini btn-primary'

  .row
    .col-md-12
      %table.table
        %tr
          %td.col-md-2
            %b Description
          %td
            = markdown(@booth.description)
        %tr
          %td.col-md-2
            %b Reasoning
          %td
            = markdown(@booth.reasoning)
        %tr
          %td.col-md-2
            %b Website
          %td
            - if @booth.website_url.present?
              = link_to @booth.website_url,  @booth.website_url
        %tr
          %td.col-md-2
            %b Submitter
          %td
            = link_to @booth.submitter.name, user_path(@booth.submitter)
        %tr
          %td.col-md-2
            %b Submitter's relationship
          %td
            = @booth.submitter_relationship
        %tr
          %td.col-md-2
            %b Responsibles
          %td
            - @booth.responsibles.each_with_index do |responsibles, i|
              .responsibles
                = link_to responsibles.name, user_path(responsibles)
                - if responsibles.email_public
                  (
                  = responsibles.email
                  )
                = ", " unless i == @booth.responsibles.length - 1
        %tr
          %td.col-md-2
            %b Submitted on
          %td
            = @booth.created_at
        %tr
          %td.col-md-2
            %b Last updated on
          %td
            = @booth.updated_at