config/routes.rb
Osem::Application.routes.draw do
  # concerns
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  # Problem children
  get '/2017',
    to: redirect('http://2017.linuxfestnorthwest.org/2017', status: 302)

  # Root
  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  # short urls
  if ENV['OSEM_ROOT_CONFERENCE'].present?
    get '/register', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/register/new")
    get '/schedule', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/schedule/events")
  end


  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path:        'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  get '/checkin',
    to: redirect('/admin/ticket_scannings', status: 302)

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resources :ticket_scannings, only: [:index, :create, :new]
    get '/scan_ticket/:token' => 'ticket_scannings#new', as: 'scan_ticket'


    resources :comments, only: [:index]
    resources :conferences do
      resources :surveys do
        resources :survey_questions, except: :index
      end
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations do
        member do
          patch :toggle_attendance
          patch :toggle_code_of_conduct
        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events, concerns: [:with_datatable] do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          collection do
            get :voting_queue
            get :speakers
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets do
        get 'materials', on: :collection
        post 'import', on: :collection
        post 'give', on: :member
      end
      resources :sponsors, except: [:show] do
        post 'import', on: :collection
      end
      resources :lodgings, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        post 'import', on: :collection
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences, 'code-of-conduct'
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resources :surveys, only: [:index, :show] do
      member do
        post :reply
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
        get :kiosk
        get :print
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  unless ENV['OSEM_ROOT_CONFERENCE'].blank?
    root to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}")
  else
    root to: 'conferences#index', via: [:get, :options]
  end
end

app/models/event_type.rb
# frozen_string_literal: true

class EventType < ApplicationRecord
  belongs_to :program, touch: true
  has_many :events, dependent: :restrict_with_error

  has_paper_trail meta:   { conference_id: :conference_id },
                  ignore: %i[updated_at]

  validates :title, presence: true
  validates :length, numericality: {greater_than: 0}
  validates :minimum_abstract_length, presence: true
  validates :maximum_abstract_length, presence: true
  validate :length_step
  validates :color, format: /\A#[0-9A-F]{6}\z/

  before_validation :capitalize_color

  alias_attribute :name, :title

  private

  ##
  # Check if length is a divisor of program schedule cell size. Used as validation.
  #
  def length_step
    errors.add(:length, "must be a divisor of #{program.schedule_interval}") if program && length % program.schedule_interval != 0
  end

  def capitalize_color
    self.color = color.upcase if color.present?
  end

  def conference_id
    program.conference_id
  end
end

app/controllers/api/v1/events_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class EventsController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      # Disable forgery protection for any json requests. This is required for jsonp support
      skip_before_action :verify_authenticity_token

      def index
        events = Event.includes(:track, :event_type, event_users: :user)

        if @conference
          events = events.where(program: @conference.program)
        end

        respond_with events.confirmed, callback: params[:callback]
      end
    end
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  ##
  # Includes functions related to events
  ##
  ##
  # ====Returns
  # * +String+ -> number of registrations / max allowed registrations
  def registered_text(event)
    return "Registered: #{event.registrations.count}/#{event.max_attendees}" if event.max_attendees

    "Registered: #{event.registrations.count}"
  end

  def rating_stars(rating, max, options = {})
    Array.new(max) do |counter|
      content_tag(
        'label',
        '',
        class: "rating#{' bright' if rating.to_f > counter}",
        **options
      )
    end.join.html_safe
  end

  def rating_fraction(rating, max, options = {})
    content_tag('span', "#{rating}/#{max}", **options)
  end

  def replacement_event_notice(event_schedule)
    if event_schedule.present? && event_schedule.replacement?(@withdrawn_event_schedules)
      replaced_event = event_schedule.replaced_event_schedule.try(:event)
      content_tag :span do
        concat content_tag :span, 'Please note that this talk replaces '
        concat link_to replaced_event.title, conference_program_proposal_path(@conference.short_title, replaced_event.id)
      end
    end
  end

  def canceled_replacement_event_label(event, event_schedule, *label_classes)
    if event.state == 'canceled' || event.state == 'withdrawn'
      content_tag :span, 'CANCELED', class: (['label', 'label-danger'] + label_classes)
    elsif event_schedule.present? && event_schedule.replacement?(@withdrawn_event_schedules)
      content_tag :span, 'REPLACEMENT', class: (['label', 'label-info'] + label_classes)
    end
  end

  def track_selector_input(form)
    if @program.tracks.confirmed.cfp_active.any?
      form.input :track_id, as:            :select,
                            collection:    @program.tracks.confirmed.cfp_active.pluck(:name, :id),
                            include_blank: '(Please select)'
    end
  end

  def rating_tooltip(event, max_rating)
    "#{event.average_rating}/#{max_rating}, #{pluralize(event.voters.length, 'vote')}"
  end

  def event_type_dropdown(event, event_types, conference_id)
    selection = event.event_type.try(:title) || 'Event Type'
    options = event_types.collect do |event_type|
      [
        event_type.title,
        admin_conference_program_event_path(
          conference_id,
          event,
          event: { event_type_id: event_type.id }
        )
      ]
    end
    active_dropdown(selection, options)
  end

  def track_dropdown(event, tracks, conference_id)
    selection = event.track.try(:name) || 'Track'
    options = tracks.collect do |track|
      [
        track.name,
        admin_conference_program_event_path(
          conference_id,
          event,
          event: { track_id: track.id }
        )
      ]
    end
    active_dropdown(selection, options)
  end

  def difficulty_dropdown(event, difficulties, conference_id)
    selection = event.difficulty_level.try(:title) || 'Difficulty'
    options = difficulties.collect do |difficulty|
      [
        difficulty.title,
        admin_conference_program_event_path(
          conference_id,
          event,
          event: { difficulty_level_id: difficulty.id }
        )
      ]
    end
    active_dropdown(selection, options)
  end

  def state_dropdown(event, conference_id, email_settings)
    selection = event.state.humanize
    options = []
    if event.transition_possible? :accept
      options << [
        'Accept',
        accept_admin_conference_program_event_path(conference_id, event)
      ]
      if email_settings.send_on_accepted?
        options << [
          'Accept (without email)',
          accept_admin_conference_program_event_path(
            conference_id,
            event,
            send_mail: false
          )
        ]
      end
    end
    if event.transition_possible? :reject
      options << [
        'Reject',
        reject_admin_conference_program_event_path(conference_id, event)
      ]
      if email_settings.send_on_rejected?
        options << [
          'Reject (without email)',
          reject_admin_conference_program_event_path(
            conference_id,
            event,
            send_mail: false
          )
        ]
      end
    end
    if event.transition_possible? :restart
      options << [
        'Start review',
        restart_admin_conference_program_event_path(conference_id, event)
      ]
    end
    if event.transition_possible? :confirm
      options << [
        'Confirm',
        confirm_admin_conference_program_event_path(conference_id, event)
      ]
    end
    if event.transition_possible? :cancel
      options << [
        'Cancel',
        cancel_admin_conference_program_event_path(conference_id, event)
      ]
    end
    active_dropdown(selection, options)
  end

  def event_switch_checkbox(event, attribute, conference_id)
    check_box_tag(
      conference_id,
      event.id,
      event.send(attribute),
      url:   admin_conference_program_event_path(
        conference_id,
        event,
        event: { attribute => nil }
      ),
      class: 'switch-checkbox'
    )
  end

  private

  def active_dropdown(selection, options)
    # Consistent rendering of dropdown lists that submit patched changes
    #
    # Selection is the string to show by default, which is clicked to expose the
    # dropdown options.
    # Options is a list of 2-item lists; for each entry:
    # * [0] is the text of the option,
    # * [1] is the link url for the options
    content_tag('div', class: 'dropdown') do
      content_tag(
        'a',
        class: 'dropdown-toggle',
        href:  '#',
        data:  { toggle: 'dropdown' }
      ) do
        content_tag('span', selection) +
          content_tag('span', '', class: 'caret')
      end +
        content_tag('ul', class: 'dropdown-menu') do
          options.collect do |option|
            content_tag('li', link_to(option[0], option[1], method: :patch))
          end.join.html_safe
        end
    end
  end
end

app/views/admin/events/_all_with_comments.csv.haml
- headers = ['Event ID',
             'Title',
             'Abstract',
             'Start time',
             'Submitter',
             'Speaker',
             'Speaker Email',
             'Event Type',
             'Track',
             'Difficulty Level',
             'Room',
             'State',
             'Comments']
= CSV.generate_line ["Events with Comments"]
= CSV.generate_line headers
- @events.each do |event|
  - all_comments = ''
  - event.root_comments.each do |comment|
    - all_comments << "#{comment.created_at.strftime("%Y-%m-%d")} #{comment.created_at.strftime("%I:%M%p")}  #{comment.user.name}: #{comment.body}\n"
  = CSV.generate_line([event.id,
                       event.title,
                       event.abstract,
                       (event.time.present? ? "#{event.time.strftime("%Y-%m-%d")}#{event.time.strftime("%I:%M%p")} " : ''),
                       event.submitter.name,
                       event.speaker_names,
                       event.speaker_emails,
                       event.event_type.title,
                       (event.track.present? ? event.track.name : ''),
                       (event.difficulty_level.present? ? event.difficulty_level.title : ''),
                       (event.room.present? ? event.room.name : ''),
                       event.state,
                       all_comments]).html_safe

app/views/admin/events/_confirmed_events.csv.haml
- headers = ['Event ID',
             'Title',
             'Abstract',
             'Start time',
             'Submitter',
             'Speaker',
             'Speaker Email',
             'Event Type',
             'Track',
             'Difficulty Level',
             'Room',
             'State']
= CSV.generate_line ["Confirmed Events"]
= CSV.generate_line headers
- @events.confirmed.each do |event|
  = CSV.generate_line([event.id,
                       event.title,
                       event.abstract,
                       (event.time.present? ? "#{event.time.strftime("%Y-%m-%d")} #{event.time.strftime("%I:%M%p")} " : ''),
                       event.submitter.name,
                       event.speaker_names,
                       event.speaker_emails,
                       event.event_type.title,
                       (event.track.present? ? event.track.name : ''),
                       (event.difficulty_level.present? ? event.difficulty_level.title : ''),
                       (event.room.present? ? event.room.name : ''),
                       event.state]).html_safe

app/views/admin/events/_datatable_row.haml
- cache ['admin', conference_id, program, event] do
  %tr{ id: "event-#{event.id}" }
    %td
      = event.id

    %td
      = link_to event.title,
        admin_conference_program_event_path(conference_id, event)

    - if rating_enabled
      %td.col-md-1{ data: { order: event.average_rating } }
        = render 'datatable_row_rating',
          event:      event,
          show_votes: show_votes,
          max_rating: max_rating

    - if event.submitter
      %td
        = link_to event.submitter.name, admin_user_path(event.submitter)
        - unless event.submitter.registrations.for_conference(event.conference)
          %span.label.label-warning Unregistered
    - else
      %td.bg-danger
        Unknown submitter

    %td
      - event.speakers_ordered.each do |speaker|
        .speaker
          = link_to speaker.name, admin_user_path(speaker)
          - unless speaker.registrations.for_conference(event.conference)
            %span.label.label-danger Unregistered

    - if @program.languages.present?
      %td
        = event.language

    %td.text-center{ data: { order: event.require_registration.to_s } }
      = event_switch_checkbox(event, :require_registration, conference_id)
      - if event.require_registration
        = link_to registered_text(event),
          registrations_admin_conference_program_event_path(conference_id,
            event),
          class: 'btn btn-xs btn-default'

    %td.text-center{ data: { order: event.is_highlight.to_s } }
      = event_switch_checkbox(event, :is_highlight, conference_id)

    %td
      = event_type_dropdown(event, event_types, conference_id)

    %td
      = track_dropdown(event, tracks, conference_id)

    %td
      = difficulty_dropdown(event, difficulty_levels, conference_id)

    %td
      = state_dropdown(event, conference_id, email_settings)

    %td.text-center
      = link_to "#{event.comments_count}",
        admin_conference_program_event_path(conference_id, event),
        anchor: 'comments-div'
    %td.text-center
      = link_to new_admin_conference_survey_path(@conference.short_title,
        survey: {  surveyable_type: 'Event', surveyable_id: event.id }),
        class: 'btn btn-success' do
        .fa.fa-plus

app/views/admin/events/_datatable_row_rating.haml
- if show_votes
  %div{ data: { toggle: 'tooltip' }, title: rating_tooltip(event, max_rating) }<
    = rating_stars(event.average_rating, max_rating, avgrate: true)

.clearfix
  - if event.voted?(current_user)
    %span.label.label-success
      You voted:
      = rating_fraction(event.user_rating(current_user), max_rating)
  - else
    %span.label.label-danger
      Not rated

app/views/admin/events/_export_menu.haml
.btn-group
  %button.btn.btn-success.dropdown-toggle{ data: { toggle: 'dropdown' } }
    Export
    = export_format.upcase
    %span.caret
  %ul.dropdown-menu{ role: 'menu' }
    %li
      = link_to 'All Events',
        admin_conference_program_events_path(conference_id,
          format: export_format,
          event_export_option: 'all')
    %li
      = link_to 'Confirmed Events',
        admin_conference_program_events_path(conference_id,
          format: export_format,
          event_export_option: 'confirmed')
    %li
      = link_to 'All Events with Comments',
        admin_conference_program_events_path(conference_id,
          format: export_format,
          event_export_option: 'all_with_comments')

app/views/admin/events/_nested_comments.html.haml
%div{ style: "padding-left:#{padding}px" }
  .well.comment-section
    %strong= comment.user.name
    %i= comment.created_at
    %p.comment-body= comment.body
    %div
      %a.pull-right.comment-reply-link{ href: '#' } Reply
      .comment-reply
        = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, comment.commentable_id), method: :post do |f|
          = f.input :body
          %input{ name: 'parent', type: 'hidden', value: comment.id }
          %input{ name: 'authenticity_token', type: 'hidden', value: '#{form_authenticity_token}' }
          %button.btn.btn-primary.pull-right{ name: 'button', type: 'submit' } Add Reply
  - comment.children.each do |child|
    = render 'nested_comments', comment: child, padding: 50

app/views/admin/events/_proposal.html.haml
- cache ['admin/event', @conference, @program, @event] do
  .row
    .col-md-12
      %h3
        = @event.title
        %br
        %small
          = @event.subtitle
        .btn-group.pull-right
          = link_to 'Registrations', registrations_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-success'
          = link_to 'Public view', conference_program_proposal_path(@conference.short_title, @event), class: 'btn btn-mini btn-info'
          = link_to 'Edit', edit_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-mini btn-primary'

  .row
    .col-md-12
      %table.table
        %tr
          %td.col-md-2
            %b Type
          %td
            = event_type_dropdown(@event, @event_types, @conference.short_title)
        %tr
          %td
            %b Highlight
          %td
            = event_switch_checkbox(@event, :is_highlight, @conference.short_title)
        %tr
          %td
            %b State
          %td
            = state_dropdown(@event, @conference.short_title, @conference.email_settings)
        %tr
          %td
            %b Track
          %td
            = track_dropdown(@event, @tracks, @conference.short_title)
        %tr
          %td
            %b Difficulty
          %td
            = difficulty_dropdown(@event, @difficulty_levels, @conference.short_title)
        %tr
          %td
            %b Requires Registration
          %td
            = event_switch_checkbox(@event, :require_registration, @conference.short_title)
            - if @event.require_registration
              = registered_text(@event)

        - if @program.languages.present?
          %tr
            %td
              %b Language
            %td
              = @event.language

        - unless @event.room.nil?
          %tr
            %td
              %b Room
            %td
              = @event.room.name
        - unless @event.time.nil?
          %tr
            %td
              %b Scheduled time
            %td
              = time_with_timezone(@event.time)
        %tr
          %td
            %b Submitter
          %td
            = link_to @event.submitter.name, admin_user_path(@event.submitter)
            - if @event.submitter.email_public
              (
              = link_to @event.submitter.email, "mailto: #{@event.submitter.email}"
              )
        %tr
          %td
            %b Speakers
          %td
            - @event.speakers.each do |speaker|
              %div
                = link_to speaker.name, admin_user_path(speaker)
                - if speaker.email_public
                  (
                  = link_to speaker.email, "mailto: #{speaker.email}"
                  )
        %tr
          %td
            %b Biographies
          %td
            - @event.speakers.each do |speaker|
              - unless speaker.biography.blank?
                %b
                  = speaker.name
                = markdown(speaker.biography)
        %tr
          %td
            %b Submitted on
          %td= @event.created_at
        %tr
          %td
            %b Last updated on
          %td= @event.updated_at
        %tr
          %td
            %b Abstract
          %td= markdown(@event.abstract)
        %tr
          %td
            %b Requirements
          %td= simple_format(@event.description)

        - if @conference.program.rating_enabled?
          = render 'voting',
            event:         @event,
            show_votes:    @program.show_voting?,
            max_rating:    @program.rating,
            voting_period: @program.voting_period?,
            votes:         @votes,
            conference_id: @conference.short_title

- cache [@conference, @event, @comments] do
  .row
    = link_to "Comments (#{@comment_count})", '#', id: 'event-comment-link'
    #comments-div
      %hr
      %ul.media
        %div
          .row-fluid
            = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, @event.id), method: :post do |f|
              = f.input :body
              = f.submit 'Add Comment', class: 'btn btn-primary pull-right'
          %br
          %br
          - @comments.each do |comment|
            %div
              = render partial: 'nested_comments', locals: { comment: comment, padding: 0}

app/views/admin/events/_user_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :email
    = f.input :name
  = remove_association_link :user, f

app/views/admin/events/edit.html.haml
= render 'proposals/form'

app/views/admin/events/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    %li.active
      = link_to 'Proposal', '#proposal-content', 'data-toggle' => 'tab'
    %li
      = link_to 'History', '#history-content', 'data-toggle' => 'tab'
    %li
      %a{ href: '#proposal-tasks', 'data-toggle' => 'tab' }
        Tasks
        %span.label.label-danger{ style: 'border-radius: 1em;' }
          - progress_status = @event.progress_status
          = progress_status.reject{ |_key, value| value || value.nil? }.length
    %li
      = link_to 'Commercials', '#proposal-commercials', 'data-toggle' => 'tab'

  .tab-content
    #proposal-content.tab-pane.active
      = render 'proposal'
    #history-content.tab-pane
      .col-md-12
        %table.datatable
          %thead
            %th ID
            %th Description
            %th Actions
          %tbody
            - @versions.each do |version|
              %tr
                %td
                  = version.id
                %td
                  %p
                    = link_to_user(version.whodunnit)

                    - if version.item_type == 'Event'
                      = event_change_description(version)
                      = "event #{@event.title}"

                    - elsif version.item_type == 'Vote'
                      = vote_change_description(version)
                      = "event #{@event.title}"

                    - else
                      = general_change_description(version)
                      =  link_to 'commercial',
                                edit_admin_conference_program_event_path(conference_id: @conference.short_title,
                                        id: @event.id, anchor: 'commercials-content')

                    %small.text-muted
                      = distance_of_time_in_words(Time.now, version.created_at) + ' ago'
                      %br
                      = "(#{version.created_at.strftime('%B %-d, %Y %H:%M')})"

                  %br
                  = render partial: 'shared/object_changes', locals: { version: version }
                %td
                  = render partial: 'shared/changelog_actions', locals: { version: version }

    #proposal-tasks.tab-pane
      - progress_percentage = @event.calculate_progress
      .col-md-12
        %h3
          = @event.title
        %br
        %table.table.table-hover
          %tr
            %td= link_to "#{'Speaker'.pluralize(@event.speakers.count)} must be registered to the conference", admin_conference_registrations_path(@event.program.conference.short_title)
            %td{ 'class' => class_for_todo(progress_status['registered']) }
              %span{ 'class' => [icon_for_todo(progress_status['registered']), 'fa-lg'] }
          %tr
            %td
              - if @event.speakers.count == 1
                = link_to 'Fill out speaker\'s biography', edit_admin_user_path(@event.speakers.first)
              - else
                Fill out speaker's biography:
                = speaker_links(@event)
            %td{ 'class' => class_for_todo(progress_status['biographies']) }
              %span{ 'class' => [icon_for_todo(progress_status['biographies']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a subtitle', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
            %td{ 'class' => class_for_todo(progress_status['subtitle']) }
              %span{ 'class' => [icon_for_todo(progress_status['subtitle']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a commercial', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event, anchor: 'commercials-content')
            %td{ 'class' => class_for_todo(progress_status['commercials']) }
              %span{ 'class' => [icon_for_todo(progress_status['commercials']), 'fa-lg'] }
          - unless progress_status['track'].nil?
            %tr
              %td= link_to 'Add a track', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
              %td{ 'class' => class_for_todo(progress_status['track']) }
                %span{ 'class' => [icon_for_todo(progress_status['track']), 'fa-lg'] }
          %tr
            %td= link_to 'Add a difficulty level', edit_admin_conference_program_event_path(@event.program.conference.short_title, @event)
            %td{ 'class' => class_for_todo(progress_status['difficulty_level']) }
              %span{ 'class' => [icon_for_todo(progress_status['difficulty_level']), 'fa-lg'] }
    #proposal-commercials.tab-pane
      = render partial: 'shared/media_items', locals: { commercials: @event.commercials }