config/routes.rb
Osem::Application.routes.draw do
  # concerns
  concern :with_datatable do
    post 'datatable', on: :collection
  end

  # Problem children
  get '/2017',
    to: redirect('http://2017.linuxfestnorthwest.org/2017', status: 302)

  # Root
  constraints DomainConstraint do
    get '/', to: 'conferences#show'
  end

  # short urls
  if ENV['OSEM_ROOT_CONFERENCE'].present?
    get '/register', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/register/new")
    get '/schedule', to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}/schedule/events")
  end


  if ENV['OSEM_ICHAIN_ENABLED'] == 'true'
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path:        'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy] do
    resources :openids, only: :destroy
  end

  get '/checkin',
    to: redirect('/admin/ticket_scannings', status: 302)

  namespace :admin do
    resources :organizations do
      member do
        get :admins
        post :assign_org_admins
        delete :unassign_org_admins
      end
    end
    resources :users do
      member do
        patch :toggle_confirmation
      end
    end
    resources :ticket_scannings, only: [:index, :create, :new]
    get '/scan_ticket/:token' => 'ticket_scannings#new', as: 'scan_ticket'


    resources :comments, only: [:index]
    resources :conferences do
      resources :surveys do
        resources :survey_questions, except: :index
      end
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :schedules, except: [:edit, :update]
      resources :event_schedules, only: [:create, :update, :destroy]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :booths do
        member do
          patch :accept
          patch :restart
          patch :to_accept
          patch :reject
          patch :reset
          patch :to_reject
          patch :cancel
          patch :confirm
        end
      end

      resources :registrations do
        member do
          patch :toggle_attendance
          patch :toggle_code_of_conduct
        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        get 'venue_commercial/render_commercial' => 'venue_commercials#render_commercial'
        resource :venue_commercial, only: [:create, :update, :destroy]
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resources :cfps
        resources :tracks do
          member do
            patch :toggle_cfp_inclusion
            patch :restart
            patch :to_accept
            patch :accept
            patch :confirm
            patch :to_reject
            patch :reject
            patch :cancel
            patch :update_selected_schedule
          end
          resources :roles, only: [:show, :edit, :update] do
            member do
              post :toggle_user
            end
          end
        end
        resources :event_types
        resources :difficulty_levels
        post 'mass_upload_commercials' => 'commercials#mass_upload'
        resources :events, concerns: [:with_datatable] do
          member do
            patch :toggle_attendance
            get :registrations
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          collection do
            get :voting_queue
            get :speakers
          end
        end
        resources :reports, only: :index
      end

      resources :resources
      resources :tickets do
        get 'materials', on: :collection
        post 'import', on: :collection
        post 'give', on: :member
      end
      resources :sponsors, except: [:show] do
        post 'import', on: :collection
      end
      resources :lodgings, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :physical_tickets, only: [:index]
      resources :roles, except: [:new, :create] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        post 'import', on: :collection
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end

      get '/revision_history' => 'versions#index'
    end

    get '/revision_history' => 'versions#index'
    get '/revision_history/:id/revert_object' => 'versions#revert_object', as: 'revision_history_revert_object'
    get '/revision_history/:id/revert_attribute' => 'versions#revert_attribute', as: 'revision_history_revert_attribute'
  end
  resources :organizations, only: [:index] do
    member do
      get :conferences, 'code-of-conduct'
    end
  end
  resources :conferences, only: [:index, :show] do
    resources :booths do
      member do
        patch :withdraw
        patch :confirm
        patch :restart
      end
    end
    resources :surveys, only: [:index, :show] do
      member do
        post :reply
      end
    end
    resource :program, only: [] do
      resources :proposals, except: :destroy do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        member do
          get :registrations
          patch '/withdraw' => 'proposals#withdraw'
          patch '/confirm' => 'proposals#confirm'
          patch '/restart' => 'proposals#restart'
        end
      end
      resources :tracks, except: :destroy do
        member do
          patch :restart
          patch :confirm
          patch :withdraw
        end
      end
    end

    # TODO: change conference_registrations to singular resource
    resource :conference_registration, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy, :index]
    resources :payments, only: [:index, :new, :create]
    resources :physical_tickets, only: [:index, :show]
    resource :subscriptions, only: [:create, :destroy]
    resource :schedule, only: [:show] do
      member do
        get :events
        get :kiosk
        get :print
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conferences')

  unless ENV['OSEM_ROOT_CONFERENCE'].blank?
    root to: redirect("/conferences/#{ENV['OSEM_ROOT_CONFERENCE']}")
  else
    root to: 'conferences#index', via: [:get, :options]
  end
end

app/controllers/admin/conferences_controller.rb
# frozen_string_literal: true

module Admin
  class ConferencesController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_resource :program, through: :conference, singleton: true, except: :index
    load_resource :user, only: [:remove_user]

    def index
      # Redirect to new form if there is no conference
      if Conference.count == 0
        redirect_to new_admin_conference_path
        return
      end

      @total_user = User.count
      @new_user = User.where('created_at > ?', current_user.last_sign_in_at).count

      @total_reg = Registration.count
      @new_reg = Registration.where('created_at > ?', current_user.last_sign_in_at).count

      @total_submissions = Event.count
      @new_submissions = Event.where('created_at > ?', current_user.last_sign_in_at).count

      @total_withdrawn = Event.where(state: :withdrawn).count
      @new_withdrawn = Event
          .where('state = ? and created_at > ?', 'withdrawn', current_user.last_sign_in_at).count

      @active_conferences = Conference.get_active_conferences_for_dashboard # pending or the last two
      @deactive_conferences = Conference
          .get_conferences_without_active_for_dashboard(@active_conferences) # conferences without active
      @conferences = @active_conferences + @deactive_conferences

      @recent_users = User.limit(5).order(created_at: :desc)
      @recent_events = Event.limit(5).order(created_at: :desc)
      @recent_registrations = Registration.limit(5).order(created_at: :desc)

      @top_submitter = Conference.get_top_submitter

      @registrations = []
      @submissions = []
      @tickets = []

      @conferences.each do |c|
        # Conference registrations over time chart
        @registrations << {
          name: c.short_title,
          data: c.get_registrations_per_week
        }
        # Event submissions over time chart
        @submissions << {
          name: c.short_title,
          data: c.get_submissions_per_week
        }
        # Tickets sold over time chart
        @tickets << {
          name: c.short_title,
          data: c.get_tickets_sold_per_week
        }
      end

      @event_distribution = Conference.event_distribution
      @event_distribution_colors = Event::COLORS.values

      @user_distribution = User.distribution
      @user_distribution_colors = User::DISTRIBUTION_COLORS.values
    end

    def new
      @conference = Conference.new
      @organizations = Organization.accessible_by(current_ability, :update).pluck(:name, :id)
    end

    def create
      @conference = Conference.new(conference_params)

      if @conference.save
        # user that creates the conference becomes organizer of that conference
        current_user.add_role :organizer, @conference

        redirect_to admin_conference_path(id: @conference.short_title),
                    notice: 'Conference was successfully created.'
      else
        flash.now[:error] = 'Could not create conference. ' + @conference.errors.full_messages.to_sentence
        render action: 'new'
      end
    end

    def update
      short_title = @conference.short_title
      @conference.assign_attributes(conference_params)
      send_mail_on_conf_update = @conference.notify_on_dates_changed?

      if @conference.update_attributes(conference_params)
        ConferenceDateUpdateMailJob.perform_later(@conference) if send_mail_on_conf_update
        redirect_to edit_admin_conference_path(id: @conference.short_title),
                    notice: 'Conference was successfully updated.'
      else
        redirect_to edit_admin_conference_path(id: short_title),
                    error: 'Updating conference failed. ' \
                    "#{@conference.errors.full_messages.join('. ')}."
      end
    end

    def show
      @program = @conference.program || Program.new(conference_id: @conference.id)

      # Overview and since last login information
      @total_reg = @conference.registrations.count
      @new_reg = @conference.registrations.where('created_at > ?', current_user.last_sign_in_at).count

      @all_events = @program.events

      @total_submissions = @all_events.count
      @new_submissions = @all_events
          .where('created_at > ?', current_user.last_sign_in_at).count

      @program_length = @conference.current_program_hours
      @new_program_length = @conference.new_program_hours(current_user.last_sign_in_at)

      @total_withdrawn = @all_events.where(state: :withdrawn).count
      @new_withdrawn = @all_events.where(state: :withdrawn).where(
        'events.created_at > ?',
        current_user.last_sign_in_at
      ).count

      #  Step by step list
      @conference_progress = @conference.get_status

      # Line charts
      @registrations = @conference.get_registrations_per_week
      @submissions = @conference.get_submissions_data
      @tickets = @conference.get_tickets_data

      # Doughnut charts
      @event_type_distribution = @conference.event_type_distribution
      @event_type_distribution_confirmed = @conference.event_type_distribution(:confirmed)
      @event_type_distribution_withdrawn = @conference.event_type_distribution(:withdrawn)

      @difficulty_levels_distribution = @conference.difficulty_levels_distribution
      @difficulty_levels_distribution_confirmed = @conference
          .difficulty_levels_distribution(:confirmed)
      @difficulty_levels_distribution_withdrawn = @conference
          .difficulty_levels_distribution(:withdrawn)

      @tracks_distribution = @conference.tracks_distribution
      @tracks_distribution_confirmed = @conference.tracks_distribution(:confirmed)
      @tracks_distribution_withdrawn = @conference.tracks_distribution(:withdrawn)

      # Recent actions information
      @recent_events = @conference.program.events.limit(5).order(created_at: :desc)
      @recent_registrations = @conference.registrations.limit(5).order(created_at: :desc)

      @top_submitter = @conference.get_top_submitter

      respond_to do |format|
        format.html
        format.json { render json: @conference.to_json }
      end
    end

    def edit
      @conferences = Conference.all
      @date_string = date_string(@conference.start_date, @conference.end_date)
      @affected_event_count = @conference.program.events.scheduled(@conference.program.selected_schedule_id).count
      respond_to do |format|
        format.html
        format.json { render json: @conference.to_json }
      end
    end

    private

    def conference_params
      params.require(:conference).permit(:title, :short_title, :description, :timezone,
                                         :start_date, :end_date, :start_hour, :end_hour,
                                         :rooms_attributes, :tracks_attributes,
                                         :tickets_attributes, :event_types_attributes,
                                         :picture, :picture_cache, :questions_attributes,
                                         :question_ids, :answers_attributes, :answer_ids, :difficulty_levels_attributes,
                                         :use_vpositions, :use_vdays, :vdays_attributes,
                                         :vpositions_attributes, :use_volunteers, :color,
                                         :sponsorship_levels_attributes, :sponsors_attributes,
                                         :registration_limit, :organization_id, :ticket_layout,
                                         :booth_limit)
    end
  end
end

app/controllers/api/v1/conferences_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ConferencesController < Api::BaseController
      load_resource find_by: :short_title
      respond_to :json

      # Disable forgery protection for any json requests. This is required for jsonp support
      skip_before_action :verify_authenticity_token

      def index
        render json: @conferences, serializer: ConferencesArraySerializer, callback: params['callback']
      end

      def show
        render json: [@conference], serializer: ConferencesArraySerializer, callback: params['callback']
      end
    end
  end
end

app/helpers/conference_helper.rb
# frozen_string_literal: true

module ConferenceHelper
  # Return true if only call_for_papers or call_for_tracks or call_for_booths is open
  def one_call_open(*calls)
    calls.one? { |call| call.try(:open?) }
  end
  # Return true if exactly two of those calls are open: call_for_papers , call_for_tracks , call_for_booths

  def two_calls_open(*calls)
    calls.count{ |call| call.try(:open?) } == 2
  end

  # URL for sponsorship emails
  def sponsorship_mailto(conference)
    [
      'mailto:',
      conference.contact.sponsor_email,
      '?subject=',
      url_encode(conference.short_title),
      '%20Sponsorship'
    ].join
  end
end

app/views/admin/conferences/_recent_registrations.html.haml
- if recent_registrations && !recent_registrations.empty?
  .table-responsive
    %table.table
      %thead
        %tr
          %th #
          %th Public Name
          %th Conference
          %th Date
        - recent_registrations.each_with_index do |registration, index|
          %tbody
            %tr
              %td= index + 1
              %td= link_to registration.name, admin_user_path(registration.user.id)
              %td= link_to registration.conference.title, admin_conference_path(registration.conference.short_title)
              %td= registration.created_at.strftime('%m/%d/%Y')
- else
  %h5.text-warning.text-center
    No registrations!

app/views/admin/conferences/_recent_submissions.html.haml
- if recent_events && !recent_events.empty?
  .table-responsive
    %table.table
      %thead
        %tr
          %th #
          %th Submitter
          %th Title
          %th Conference
          %th Status
        - recent_events.each_with_index do |event, index|
          %tbody
            %tr
              %td= index + 1
              - if event.submitter
                %td= link_to event.submitter.name, admin_user_path(event.submitter.id)
              - else
                %td Unknown Submitter
              %td= link_to event.title, admin_conference_program_event_path(event.program.conference.short_title, event)
              %td= link_to event.program.conference.title, admin_conference_path(event.program.conference.short_title)
              %td
                .span{ 'class' => label_for(event.state) } #{event.state.humanize}
- else
  %h5.text-warning.text-center
    No submissions!

app/views/admin/conferences/_recent_users.html.haml
- if recent_users && !recent_users.empty?
  .table-responsive
    %table.table
      %thead
        %tr
          %th #
          %th E-Mail
          %th Date registered
          %th Confirmed?
      - recent_users.each_with_index do |user, index|
        %tbody
          %tr
            %td= index + 1
            %td= link_to user.email, admin_user_path(user.id)
            %td= user.created_at.strftime('%m/%d/%Y')
            %td
              = check_box_tag user.id, user.id, user.confirmed?,
                url: "/admin/users/#{user.id}/toggle_confirmation?user[to_confirm]=",
                class: 'switch-checkbox',
                readonly: true
- else
  %h5.text-warning.text-center
    No sign ups!

app/views/admin/conferences/_todo_list.html.haml
.list-group
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)}" }
    %h4
      Conference progress
    .progress
      .progress-bar{ 'role' => 'progressbar', 'aria-valuenow' => "#{conference_progress['process']}", 'aria-valuemin' => '0',
                    'aria-valuemax' => '100', 'style' => "width: #{conference_progress['process']}%;" }
        = conference_progress['process'] + '%'
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)}  #{class_for_todo(conference_progress['registration'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['registration']) }
    - if can? :update, @conference
      - if conference.registration_period
        = link_to 'Set up registration period', edit_admin_conference_registration_period_path(conference_progress['short_title'])
      - else
        = link_to 'Set up registration period', new_admin_conference_registration_period_path(conference_progress['short_title'])
    - else
      Set up registration period
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)}  #{class_for_todo(conference_progress['cfp'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['cfp']) }
    - if can? :update, Cfp.new(program_id: @program.id)
      = link_to 'Set up call for papers', admin_conference_program_cfps_path(conference_progress['short_title'])
    - else
      Set up call for papers
  %li{'class'=>"list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['venue'])}"}
    %span{'class'=>icon_for_todo(conference_progress['venue'])}
    - if can? :update, Venue.new(conference: @conference)
      - @conference.reload
      - if conference.venue
        = link_to 'Add venue', edit_admin_conference_venue_path(conference_progress['short_title'])
      - else
        = link_to 'Add venue', new_admin_conference_venue_path(conference_progress['short_title'])
    - else
      - @conference.reload
      Add venue
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['rooms'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['rooms']) }
    - if @conference.venue && (can? :update, @conference.venue.rooms.build)
      = link_to 'Add rooms', admin_conference_venue_rooms_path(conference_progress['short_title'])
    - else
      Add rooms
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['tracks'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['tracks']) }
    - if can? :update, @conference.program.tracks.build
      = link_to 'Add tracks', admin_conference_program_tracks_path(conference_progress['short_title'])
    - else
      Add tracks
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['event_types'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['event_types']) }
    - if can? :update, @conference.program.event_types.build
      = link_to 'Add event types', admin_conference_program_event_types_path(conference_progress['short_title'])
    - else
      Add event types
  %li{ 'class' => "list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['difficulty_levels'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['difficulty_levels']) }
    - if can? :update, @conference.program.difficulty_levels.build
      = link_to 'Add difficulty levels', admin_conference_program_difficulty_levels_path(conference_progress['short_title'])
    - else
      Add difficulty levels
  %li{ class: "list-group-item #{hidden_if_conference_over(conference)} #{class_for_todo(conference_progress['splashpage'])}" }
    %span{ 'class' => icon_for_todo(conference_progress['splashpage']) }
    - if can? :update, @conference
      = link_to 'Set up a Splashpage', admin_conference_splashpage_path(conference_progress['short_title'])
    - else
      Set up a Splashpage

app/views/admin/conferences/_top_submitter.html.haml
.row
  .col-md-12
    %h3
      Top Submitter
    - if @top_submitter && !@top_submitter.empty?
      - @top_submitter.each do |key, value|
        .row.top-submitter
          .col-md-2
            = image_tag(key.picture(25), title: "Yo #{key.name}!", alt: '', 'class' => 'img-circle img-responsive text-center', width: 25)
          .col-md-10
            %h4
              = link_to key.name, admin_user_path(key)
              %div
                %small
                  = link_to pluralize(value, 'submission'), admin_user_path(key, tab: 'submissions-content')
    - else
      %h4.text-warning
        No submissions!

app/views/admin/conferences/edit.html.haml
.row
  .col-md-12
    .page-header
      %h1 Basics
      %p.text-muted
        The most basic settings of your conference
.row
  .col-md-8
    = semantic_form_for(@conference, url: admin_conference_path(@conference.short_title), html: {multipart: true}) do |f|
      = f.input :title, hint: "The full title of the conference, e.g. 'openSUSE Conference 2014'"
      = f.input :short_title, hint: "A short title, e.g. 'oSC14', to be used in URLs"
      = f.input :description, hint: markdown_hint('A description of the conference.'), input_html: { rows: 5, data: { provide: 'markdown-editable' } }
      = f.input :color, hint: 'The color will be used eg for the dashboard.', input_html: {size: 6, type: 'color'}
      = f.label 'Conference Logo'
      %br
      - if @conference.picture?
        = image_tag @conference.picture.thumb.url
      = f.input :picture, label: false, hint: 'This will be displayed on the front page.'
      = f.hidden_field :picture_cache
      = f.input :ticket_layout, as: :select, collection: Conference.ticket_layouts.keys, hint: "Layout type for tickets of the conference."
      = f.inputs name: 'Scheduling' do
        = f.input :timezone, as: :time_zone, hint: 'The conference time zone'
        = f.input :start_date, as: :string, input_html: { id: 'conference-start-datepicker', readonly: 'readonly' }
        = f.input :end_date, as: :string, input_html: { id: 'conference-end-datepicker', readonly: 'readonly' }
        = f.input :start_hour, input_html: {size: 2, type: 'number', min: 0, max: 23}, hint: rescheduling_hint(@affected_event_count)
        = f.input :end_hour, input_html: {size: 2, type: 'number', min: 1, max: 24}, hint: rescheduling_hint(@affected_event_count)
      = f.inputs name: 'Registrations' do
        = f.input :registration_limit, as: :number, in: 0..9999, hint: 'Limit the number of registrations to the conference (0 no limit). Please note that the registration limit doesn\'t apply to speakers of confirmed events (they will still be able to register even if it has been reached). You currently have ' + pluralize(@conference.registrations.count, 'registration')
      = f.inputs name: 'Booths' do
        = f.input :booth_limit, as: :number, in: 0..9999,
        hint: 'Booth limit is the maximum number of booths that you can accept for this conference. By setting this number (0 no limit) you can be sure that you are not going to accept more booths than the conference can accommodate. You currently have ' + pluralize(@conference.booths.accepted.count, 'accepted booth') +'.'
      = f.action :submit, as: :button, button_html: { class: 'btn btn-primary', data: { confirm: 'Are you sure you want to proceed?' } }

app/views/admin/conferences/index.html.haml
.row
  .col-sm-3.col-xs-3
    = render "big_statistic",
      icon: "user", subtitle: "User", value: @total_user, delta: @new_user
  .col-sm-3.col-xs-3
    = render "big_statistic",
      icon: "check-square", subtitle: "Registration", value: @total_reg, delta: @new_reg
  .col-sm-3.col-xs-3
    = render "big_statistic",
      icon: "file-text", subtitle: "Submission", value: @total_submissions, delta: @new_submissions
  .col-sm-3.col-xs-3
    = render "big_statistic",
      icon: "archive", subtitle: "Withdrawn", value: @total_withdrawn, delta: @new_withdrawn, reverse: true

.row#registrations
  .col-md-8
    = render 'line_chart', title: 'Registrations per week', data: @registrations
  .col-md-4
    = render 'donut_chart', title: 'Events',
      data: @event_distribution, colors: @event_distribution_colors
.row#submissions
  .col-md-8
    = render 'line_chart', title: 'Submissions per week', data: @submissions
  .col-md-4
    = render 'donut_chart', title: 'Users',
      data: @user_distribution,  colors: @user_distribution_colors
.row#tickets
  .col-md-8
    = render 'line_chart', title: 'Tickets sold per week', data: @tickets
%br
.row
  .col-md-8
    %ul.nav.nav-tabs#recentTable
      %li.active
        %a{ href: '#recent_user', 'data-toggle' => 'tab' }
          %span.fa.fa-user
          Recent Users
      %li
        %a{ href: '#recent_reg', 'data-toggle' => 'tab' }
          %span.fa.fa-check-square
          Recent Registrations
      %li
        %a{ href: '#recent_submissions', 'data-toggle' => 'tab' }
          %span.fa.fa-file-text
          Recent Submissions
    .tab-content
      .tab-pane.active#recent_user
        = render partial: 'recent_users', locals: {recent_users: @recent_users}
      .tab-pane#recent_reg
        = render partial: 'recent_registrations', locals: {recent_registrations: @recent_registrations}
      .tab-pane#recent_submissions
        = render partial: 'recent_submissions', locals: {recent_events: @recent_events}
  .col-md-4
    = render partial: 'top_submitter', locals: {top_submitter: @top_submitter}

app/views/admin/conferences/new.html.haml
.row
  .col-md-8
    = semantic_form_for(@conference, url: admin_conferences_path) do |f|
      = f.inputs 'Basic Information' do
        = f.input :organization, as: :select, collection: @organizations
        = f.input :title, hint: "The name of your conference as it shall appear throughout the site. Example: 'OpenSUSE Conference 2013'",
                          input_html: { required: 'required' }
        = f.input :short_title, hint: "A short and unique handle for your conference, using only letters, numbers, underscores, and dashes. This will be used to identify your conference in URLs etc. Example: 'froscon2011'",
                                input_html: { required: 'required', pattern: '[a-zA-Z0-9_-]+', title: 'Only letters, numbers, underscores, and dashes.' }, prepend: conferences_url + '/'
      = f.inputs 'Scheduling' do
        = f.input :timezone, as: :time_zone, default: Time.zone.name, hint: 'Please select in what time zone your conference will take place.'
        = f.input :start_date, as: :string, input_html: { id: 'conference-start-datepicker', required: 'required' }
        = f.input :end_date, as: :string, input_html: { id: 'conference-end-datepicker', required: 'required' }
      = f.actions do
        = f.action :submit, button_html: {class: 'btn btn-success pull-right'}